version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies from offline mirror
          command: yarn install --offline
      - run:
          name: Confirm project can build
          command: |
            yarn build:external
      - deploy:
          name: deploy next to IBM Cloud
          command: |
            if [ "${CIRCLE_BRANCH}" == "v10" ]; then
              # Install `ibmcloud` CLI
              curl -fsSL https://clis.ng.bluemix.net/install/linux | sh

              # Login and push next manifest
              ibmcloud login \
                --apikey $CLOUD_API_KEY \
                -a https://api.ng.bluemix.net \
                -o carbon-design-system \
                -s production

              ibmcloud cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
              ibmcloud cf install-plugin blue-green-deploy -f -r CF-Community

              ibmcloud cf blue-green-deploy carbon-website-next \
                -f .circleci/manifest.next.yml \
                --delete-old-apps
            fi
